name: nlp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - "--extra-index-url=https://download.pytorch.org/whl/cu124"
    - torch==2.6.0 
    - torchvision==0.21.0 
    - torchaudio==2.6.0
    - matplotlib==3.7.5
    - ml_collections==0.1.1
    - pandas==2.0.0
    - transformers==4.57.1
    - datasets==4.3.0
    - ipykernel==6.31.0
    - seaborn==0.13.2
    - comet_ml==3.54.0
    - accelerate==1.10.1

  - cmake
  - pyarrow